### PR TITLE
Provide virtual overrides for NOX::Abstract::Vector::random().

### PR DESCRIPTION
**Pull request by bavier**
Follow-up to Trilinos commit a92b8ad8d045b8f65a6c15e60fbe356c1b9b02c7

### CODE REVIEW

**Comment by boegel** [comment]
@bavier Would this fix the problem reported in #3?

**Comment by bavier** [comment]
@boegel Yes, it should.

**Comment by jhux2** [comment]
@bavier I will approve, but this should be applied against Trilinos develop, not master.

**Comment by bavier** [comment]
@jhux2 Thank you.  I don't know the specifics of how Sundance code is shared with the Trilinos codebase.  This repository does not have a 'develop' branch, so I assumed 'master'.

**Comment by jhux2** [comment]
@bavier My misunderstanding, I thought this was trilinos/Trilinos.

**Review by jhux2 — APPROVED** [review]
lgtm

**Comment by jhux2** [comment]
@bmpersc @jwillenbring If you have write-access, can you merge this?  Thanks.

**Comment by jhux2** [comment]
@bmpersc @jwillenbring ping

**Comment by jwillenbring** [comment]
Sundance is not actively maintained, so we don't guarantee it will build, but I will merge the change as requested.

**Pull request merged**
